name: terraform-ci

on:
  push:
    branches:
      - '!master'
      - '*'

permissions:
  id-token: write
  contents: read

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3   

      - name: confiture AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Exec Terraform init
        run: |
          terraform init

      - name: Exec Terraform fmt check
        run: |
          terraform fmt -recursive -check

      - name: Exec Terraform validate
        run: |
          terraform validate

      - name: Exec Terraform plan
        run: |
          terraform plan